/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import spock.lang.Specification

class AppTest extends Specification {

    def "Application responds to a health check"() {
        setup:
        def app = new App()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
