name: 'Java CI with Gradle'
description: 'Sets up JDK, Gradle, and runs tests'

inputs:
  image-name:
    description: 'Version of Gradle to setup'
    required: true
  docker-context:
    description: 'Directory to run the commands in'
    required: true
  jar-location:
    description: 'Location of the JAR file to be copied to the Docker image'
    required: true
  registry:
    description: 'Container registry to push the image to'
    required: true
    default: 'ghcr.io'

runs:
  using: 'composite'
  steps:
  - name: Log in to the Container registry
    uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
    with:
      registry: ${{ inputs.registry }}
      username: ${{ github.actor }}
      password: ${{ github.token }}

  # This step extracts tags and labels that will be applied to the specified image.
  - name: Extract metadata (tags, labels) for Docker
    id: meta
    uses: docker/metadata-action@v5
    with:
      images: ${{ inputs.registry }}/${{ inputs.image-name }}

  # This step builds and pushes the Docker image to the specified registry.
  - name: Build and push Docker image
    uses: docker/build-push-action@v5
    with:
      context: .
      push: true
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      build-args: |
        JAR_LOCATION=${{ inputs.jar-location }}
