# https://learn.microsoft.com/en-us/java/openjdk/containers
ARG BASE_IMAGE=mcr.microsoft.com/openjdk/jdk:21-distroless
FROM ${BASE_IMAGE}

# Important scope the ARG after the FROM!!!
ARG JAR_FILE_LOCN=build/libs/restapi-all.jar

# Copy the jar file
COPY $JAR_FILE_LOCN /app.jar

# Run the application
CMD ["-Xmx256m", "-jar", "/app.jar"]