name: 'Container Image Scan'
description: 'Scan a Docker image for vulnerabilities using Trivy'

inputs:
  image-tag:
    description: 'Full name of the image'
    required: true
  registry:
    description: 'Image Registry'
    required: true
    default: 'ghcr.io'

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v4

  - name: Log in to the Container registry
    uses: docker/login-action@v3
    with:
      registry: ${{ inputs.registry }}
      username: ${{ github.actor }}
      password: ${{ github.token }}

  - name: Pull the image
    shell: bash
    run: |
      docker pull ${{ inputs.image-tag }}

  - name: Run Trivy vulnerability scanner
    uses: aquasecurity/trivy-action@0.19.0
    with:
      image-ref: ${{ inputs.image-tag }}
      format: 'sarif'
      output: 'trivy-results.sarif'
      severity: 'CRITICAL,HIGH'

  - name: Upload Trivy scan results to GitHub Security tab
    uses: github/codeql-action/upload-sarif@v3
    with:
      sarif_file: 'trivy-results.sarif'
