name: Local Docker Build
description: Locally build and tags the docker image

inputs:
  image:
    description: 'What to tag image with'
    required: true
  registry:
    description: 'Container registry to push the image to'
    required: true
    default: 'ghcr.io'
  context:
    description: 'Docker file / app location'
    required: true
    default: 'app'
  java-version:
    description: 'Version of JDK to setup'
    required: true
    default: '21'
  gradle-version:
    description: 'Version of Gradle to setup'
    required: false
    default: 'current'
  cache-encryption-key:
    description: 'The encryption key to use for gradle caching'
    required: false
  hostname:
    description: 'Hostanme to use in integration tests'
    required: false
    default: 'integration.restapi.edoatley.com'
  key-store:
    description: 'Path to keystore file (relative to docker context)'
    required: false
    default: 'src/itest/resources/itest-keystore.jks'
  key-store-password:
    secret: true
    description: 'Password for keystore'
    required: false
    default: 'itestjks'

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v4

  - name: Set up JDK
    uses: actions/setup-java@v4
    with:
      distribution: 'adopt'
      java-version: '${{ inputs.java-version }}'

  - name: Setup Gradle
    uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    with:
      gradle-version: '${{ inputs.gradle-version }}'
      cache-encryption-key: ${{ inputs.cache-encryption-key }}

  - name: Find Free Port
    id: port
    run: |
      # pick random number to start from
      INCREMENT=1
      port=$RANDOM

      while [ -n "$(ss -tan4H "sport = $port")" ]; do
        port=$((port+INCREMENT))
      done
      echo "free_port=$port"
      echo "free_port=$port" >> $GITHUB_OUTPUT
    shell: bash

  - name: Log in to the Container registry
    uses: docker/login-action@v3
    with:
      registry: ${{ inputs.registry }}
      username: ${{ github.actor }}
      password: ${{ github.token }}

  - name: Build image name
    id: extract_image
    shell: bash
    run: |
      branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
      imagename="${{ inputs.registry }}/${{ inputs.image }}:$branch"
      echo "name=$imagename"
      echo "name=$imagename" >> $GITHUB_OUTPUT

  - name: Pull the image
    run: docker pull ${{ steps.extract_image.outputs.name }}
    shell: bash

  - name: Run App as a docker image and capture startup logs
    working-directory: ${{ inputs.context }}
    env:
      # the two places the env var are used must align
      DOCKER_KEYSTORE_PATH: /keystore.jks
    run: |
      containerid=$(docker run -d \
        -p ${{ steps.port.outputs.free_port }}:8443 \
        --mount type=bind,source=$(pwd)/${{inputs.key-store}},target=${{env.DOCKER_KEYSTORE_PATH}},readonly \
        --env SERVER_KEYSTORE=${{env.DOCKER_KEYSTORE_PATH}} \
        --env SERVER_KEYSTORE_PASSWORD=${{inputs.key-store-password}} \
        --name restapi ${{ steps.extract_image.outputs.name }})
      sleep 20
      docker logs -t $containerid

    shell: bash

  - name: cURL the endpoint as a sense check
    run: "success_count=0\nfor i in {1..5}; do\n  curl -vvv -k \\\n      -H \"Host: ${{ inputs.hostname }}\" \\\n      -H \"Content-Type: application/json\" \\\n      -d '{\"username\":\"user\",\"password\":\"password\"}' \\\n      \"https://localhost:${{ steps.port.outputs.free_port }}/api/authentication\" \n  if [ $? -eq 0 ]; then\n    success_count=$((success_count+1))\n  fi\n  sleep 5\ndone\nif [ $success_count -eq 0 ]; then\n  echo \"Failed to connect to the server\"\n  docker logs --tail 200 restapi\n  exit 1\nfi\n"
    shell: bash

  - name: Run integration test
    working-directory: ${{ inputs.context }}
    env:
      SERVER_PORT: ${{ steps.port.outputs.free_port }}
      SERVER_KEYSTORE: ${{inputs.key-store}}
      SERVER_KEYSTORE_PASSWORD: ${{inputs.key-store-password}}
      SERVER_HOSTNAME: ${{inputs.hostname}}
    run: |
      gradle integrationTest
    shell: bash

  - name: Print the logs from integration tests
    run: docker logs --tail 50 restapi
    shell: bash
    if: always()

  - name: Stop Running Docker Image
    run: docker stop restapi && docker rm restapi
    shell: bash
    if: always()

  - name: Publish Test Report
    uses: mikepenz/action-junit-report@v4
    if: success() || failure() # always run even if the previous step fails
    with:
      report_paths: '**/build/test-results/integrationTest/TEST-*.xml'
