name: Local Docker Build
description: Locally build and tags the docker image

inputs:
  image:
    description: 'What to tag image with'
    required: true
  registry:
    description: 'Container registry to push the image to'
    required: true
    default: 'ghcr.io'
  context:
    description: 'Docker file / app location'
    required: true
  java-version:
    description: 'Version of JDK to setup'
    required: true
    default: '21'
  gradle-version:
    description: 'Version of Gradle to setup'
    required: false
    default: 'current'
  hostname:
    description: 'Hostanme to use in integration tests'
    required: false
    default: 'integration.restapi.edoatley.com'
  key-store:
    description: 'Path to keystore file (relative to docker context)'
    required: false
    default: 'src/itest/resources/itest-keystore.jks'
  key-store-password:
    secret: true
    description: 'Password for keystore'
    required: false
    default: 'itestjks'

runs:
  using: 'composite'
  steps:
  - name: Set up JDK
    uses: actions/setup-java@v4
    with:
      distribution: 'adopt'
      java-version: '${{ inputs.java-version }}'

  - name: Setup Gradle
    uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    with:
      gradle-version: '${{ inputs.gradle-version }}'
      cache-encryption-key: ${{ inputs.cache-encryption-key }}

  - name: Find Free Port
    id: port
    run: |
      # pick random number to start from
      INCREMENT=1
      port=$RANDOM

      while [ -n "$(ss -tan4H "sport = $port")" ]; do
        port=$((port+INCREMENT))
      done
      echo "free_port=$port"
      echo "free_port=$port" >> $GITHUB_OUTPUT
    shell: bash

  - name: Log in to the Container registry
    uses: docker/login-action@v3
    with:
      registry: ${{ inputs.registry }}
      username: ${{ github.actor }}
      password: ${{ github.token }}

  - name: Pull the image
    run: docker pull $${{inputs.registry}}/${{ inputs.image }}
    shell: bash

  - name: Run App as a docker image
    working-directory: ${{ inputs.context }}
    run: |
      docker run -d \
        -p ${{ steps.port.outputs.free_port }}:8443 \
        --mount type=bind,source=$(pwd)/${{inputs.key-store}},target=/home/app/tls/keystore.jks,readonly \
        --env SERVER_KEYSTORE_PASSWORD=${{inputs.key-store-password}} \
        --name restapi ${{ inputs.image }}
    shell: bash

  - name: Run integration test
    working-directory: ${{ inputs.context }}
    env:
      SERVER_PORT: ${{ steps.port.outputs.free_port }}
      SERVER_KEYSTORE: ${{inputs.key-store}}
      SERVER_KEYSTORE_PASSWORD: ${{inputs.key-store-password}}
      SERVER_HOSTNAME: ${{inputs.hostname}}
    run: |
      gradle integrationTest
    shell: bash

  - name: Print the logs
    run: docker logs --tail 50 restapi
    shell: bash
    if: always()

  - name: Stop Running Docker Image
    run: docker stop restapi && docker rm restapi
    shell: bash
    if: always()

  - name: Publish Test Report
    uses: mikepenz/action-junit-report@v4
    if: success() || failure() # always run even if the previous step fails
    with:
      report_paths: '**/build/test-results/integrationTest/TEST-*.xml'
