name: 'Build Java Application'
on: 
  push:

permissions:
  contents: read
  checks: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and Test
        uses: ./.github/actions/java-ci-build
        with:
          java-version: "21"
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}