name: 'Build Java Application and Docker Image'
on: 
  push:

permissions:
  contents: read
  checks: write
  id-token: write

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and Test
        uses: ./.github/actions/java-ci-build
        with:
          java-version: "21"
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
  
      - name: Upload the restapi-all.jar file to share with next workflow
        uses: actions/upload-artifact@v4
        with:
          name: restapi-all.jar
          path: app/build/libs/restapi-all.jar

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download the restapi-all.jar file from the previous job
        uses: actions/download-artifact@v4
        with:
          name: restapi-all.jar
          path: app

      - name: Docker build and push to GHCR
        uses: ./.github/actions/ghcr-docker-image
        with:
          image-name: ${{ env.IMAGE_NAME }}
          docker-context: app
          jar-location: restapi-all.jar
          