name: Azure CLI test
on:
  workflow_dispatch: 
    inputs:
      environment:
        description: 'Github Environment to use'
        required: true
        default: 'dev'
        type: choice
        options:
          - 'dev'
          - 'prod'    

          permissions:
  id-token: write
  contents: read

jobs:
  azure-cli-test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}          
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Azure Account
        run: az account show
      - name: Create Storage Account
        run: az storage account create --name edoidtest${{ inputs.environment }}zz11 --resource-group rg-edo-idtest-${{ inputs.environment }} --location uksouth --sku Standard_LRS 
      - name: Azure Resources
        run: az resource list --resource-group rg-edo-idtest-${{ inputs.environment }} --output table