name: 'Build Docker App, run and run integration tests'
on:
  push:
    branches:
      - main
      - junit5
  
permissions:
  contents: read
  checks: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Test
        uses: ./.github/actions/java-ci-build
        with:
          java-version: "21"
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
      
      - name: Run Integration Tests
        uses: ./.github/actions/integration-tests
        with:
          image: java-dev/restapi:${{ github.sha }}
          context: app