name: Build Pipeline
on: 
  push:

permissions:
  contents: read
  checks: write
  id-token: write
  security-events: write

env:
  JAVA_VERSION: "21"

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and Test
        uses: ./.github/actions/java-ci-build
        with:
          java-version: ${{ env.JAVA_VERSION }}
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
  
      - name: Upload the restapi-all.jar file to share with next workflow
        uses: actions/upload-artifact@v4
        with:
          name: restapi-all.jar
          path: app/build/libs/restapi-all.jar
          retention-days: 1
          overwrite: true

  docker-build:
    runs-on: ubuntu-latest
    needs: java-build
    outputs:
      image-tag: ${{steps.docker.outputs.image-tag }}
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Download the restapi-all.jar file from the previous job
        uses: actions/download-artifact@v4
        with:
          name: restapi-all.jar
          path: app

      - name: Docker build and push to GHCR
        uses: ./.github/actions/ghcr-docker-image  
        id: docker
        with:
          image-name: ${{ vars.IMAGE_NAME }}
          jar-location: restapi-all.jar
          dockerfile: Dockerfile.distroless
          base-image: mcr.microsoft.com/openjdk/jdk:21-distroless
          
  # could consider only running for certain branches          
  integration-tests:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v4 # need checkout before local action
      - name: Run Integration Tests
        uses: ./.github/actions/integration-tests
        with:
          image-tag: ${{ needs.docker-build.outputs.image-tag }}
          java-version: ${{ env.JAVA_VERSION }}
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}

  container-image-scan:
    runs-on: ubuntu-latest
    needs: docker-build
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4 # need checkout before local action
      - name: Run Container Image Scan
        uses: ./.github/actions/container-image-scan
        with:
          image-tag: ${{ needs.docker-build.outputs.image-tag }}

  software-composition-analysis:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v4 # need checkout before local action
      - name: Run Software Composition Analysis
        uses: ./.github/actions/software-composition-analysis
        with:
          java-version: ${{ env.JAVA_VERSION }}
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}

  release-main:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [docker-build, software-composition-analysis, container-image-scan, integration-tests]
    secrets: inherit
    uses: ./.github/workflows/main.yml
    with:
      image-name: ${{ vars.IMAGE_NAME }}
      image-tag: ${{ needs.docker-build.outputs.image-tag }}

  feature:
    if: startsWith(github.ref, 'refs/heads/feature/') && github.event_name == 'push'
    needs: [docker-build, software-composition-analysis, container-image-scan, integration-tests]
    uses: ./.github/workflows/feature.yml
    with:
      image-name: ${{ vars.IMAGE_NAME }}  # Access IMAGE_NAME here
      image-tag: ${{ needs.docker-build.outputs.image-tag }}