name: Pull Request Checks 

on:
  pull_request:
       
permissions:
  id-token: write
  contents: read
  
jobs:
  terraform:
    name: Lint Terraform
    runs-on: ubuntu-latest
    environment: nonprod
    env:
      ARM_USE_OIDC: true
      ARM_USE_AZUREAD: true
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_TERRAFORM_CLIENT_ID }}   
      TF_INSTANCE: main
  
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
  
      - name: Terraform Inspection
        uses: ./.github/actions/terraform-lint
        with:
          instance: ${{  env.TF_INSTANCE }}
          workingDir: iac/azure/static
          tfBackend: ${{  env.TF_INSTANCE }}/static
          tfParams: -var-file=instance/${{ env.TF_INSTANCE }}.tfvars 
          backendResourceGroup: ${{ vars.AZURE_TERRAFORM_STORAGE_ACC_RG }} 
          backendStorageAccount: ${{ vars.AZURE_TERRAFORM_STORAGE_ACC }}   
          backendContainer: "${{ github.repository_owner }}-${GITHUB_REPOSITORY#*/}"

# TODO: add job for the java source too